блок заданий 2
CoddeyQuinn/purple_java pull request #5
Opened 2024-12-24 23:59 UTC by CoddeyQuinn

задание 9, к сожалению, не получается до результата, прошу дать корректировки и направление мысли

2024-12-25 13:24 UTC, GitEsense requested changes
Посмотрите комментарии, может быть что-то будет полезно, надо переделать, задание конвертера "ОК", остальное исправить

2024-12-25 13:24 UTC, GitEsense commented on 9-sort-loops.js
> +            }
Не понимаю что тут должно измениться - оно никуда не ложится, Вы только "убираете" с массива значение, причём добавляете `undefined`, т.к. значения a[i] не существует, т.к. `a` существует в конкретной итерации вызова...

Вам необходимо положить значение в переменную (временную), не резать исходный массив, а взять значение и поменять местами temp = arr[2], arr[2] = arr[1], arr[1] = temp

Это как пример, так же можете почитать про трюк обмена переменными
https://learn.javascript.ru/destructuring-assignment

2024-12-25 13:24 UTC, GitEsense commented on 9-sort-loops.js
> +}
Хорошо бы создать копию исходного массива и возвращать именно её (т.е. сортировать её)

2024-12-25 13:24 UTC, GitEsense commented on 7-converter.js
> +console.log(converter(100, 'RUB', 'EUR'));
Можно приравнять к нижнему \ верхнему регистру для "удобства" ввода, если конвертируем EUR в EUR, то получим null, хотя хорошо бы возвращать "само себя"

Предложу вот такие вот варианты в качестве альтернативных вариантов решения:
**Вариант №1:**
```js
function converter(sum, currency, targetCurrency) {
    const USD = 90;
    const EUR = 100;

    currency = currency.toUpperCase();
    targetCurrency = targetCurrency.toUpperCase();

    switch (currency) {
        case 'USD':
            switch (targetCurrency) {
                case 'RUB':
                    return sum * USD;
                case 'EUR':
                    return (sum * USD) / EUR;
                default:
                    return null;
            }
        case 'EUR':
            switch (targetCurrency) {
                case 'RUB':
                    return sum * EUR;
                case 'USD':
                    return (sum * EUR) / USD;
                default:
                    return null;
            }
        case 'RUB':
            switch (targetCurrency) {
                case 'USD':
                    return sum / USD;
                case 'EUR':
                    return sum / EUR;
                default:
                    return null;
            }
        default:
            return null;
    }
}
```

**Вариант №2:**
```js
function convertSum(sum, from, to) {
    return ((sum * from) / to).toFixed(2);
}

function getTargetCurrencyIcon(targetCurrency) {
        switch (targetCurrency) {
            case 'RUB':
                return 'руб';
            case 'EUR':
                return '€';
            case 'USD':
                return '$';
            default: return '';
        }
}

function messageTemplate(value, icon){
    return `${value} ${icon}`;
}

function converter(sum, currency, targetCurrency) {
    const ALLOW_CURRENCY_LIST = ['RUB', 'EUR', 'USD'];
    const USD = 91.33;
    const RUB = 1;
    const EUR = 112.33;

    currency = currency.toUpperCase();
    targetCurrency = targetCurrency.toUpperCase();
    const icon = getTargetCurrencyIcon(targetCurrency);

    if (currency === targetCurrency) {
        return messageTemplate(sum, icon);
    }
    if (!ALLOW_CURRENCY_LIST.includes(currency)) {
        console.log('Входящая валюта мне неизвестна');
        return null;
    }
    if (!ALLOW_CURRENCY_LIST.includes(targetCurrency)) {
        console.log('Исходящая валюта мне неизвестна');
        return null;
    }
    
    let value = null;

    switch (currency) {
        case 'USD':
            switch (targetCurrency) {
                case 'RUB': value = convertSum(sum, USD, RUB); break;
                case 'EUR': value = convertSum(sum, USD, EUR); break;
            }; break;
        case 'RUB':
            switch (targetCurrency) {
                case 'USD': value = convertSum(sum, RUB, USD); break;
                case 'EUR': value = convertSum(sum, RUB, EUR); break;
            }; break;
        case 'EUR':
            switch (targetCurrency) {
                case 'RUB': value = convertSum(sum, EUR, RUB); break;
                case 'USD': value = convertSum(sum, EUR, USD); break;
            }; break;
    }

    return messageTemplate(value, icon)
}
```

**Вариант №3:**
```js
function convertSum(sum, from, to) {
    return ((sum * from) / to).toFixed(2);
}

function getTargetCurrencyIcon(targetCurrency) {
        switch (targetCurrency) {
            case 'RUB':
                return 'руб';
            case 'EUR':
                return '€';
            case 'USD':
                return '$';
            default: return '';
        }
}

function messageTemplate(value, icon){
    return `${value} ${icon}`;
}

function converter(sum, currency, targetCurrency) {
    const ALLOW_CURRENCY_LIST = [['RUB', 1], ['EUR', 112.33], ['USD', 91.33]];
    const flatList = ALLOW_CURRENCY_LIST.flat();
    currency = currency.toUpperCase();
    targetCurrency = targetCurrency.toUpperCase();

    if (!flatList.includes(currency)) {
        console.log('Входящая валюта мне неизвестна');
        return null;
    }
    if (!flatList.includes(targetCurrency)) {
        console.log('Исходящая валюта мне неизвестна');
        return null;
    }
    const icon = getTargetCurrencyIcon(targetCurrency);
    if (currency === targetCurrency) {
        return messageTemplate(sum, icon);
    }

    const currentIndex = flatList.indexOf(currency) / 2;
    const targetIndex = flatList.indexOf(targetCurrency) / 2;
    const [, currentValue] = ALLOW_CURRENCY_LIST[currentIndex];
    const [, targetValue] = ALLOW_CURRENCY_LIST[targetIndex];
    const result = convertSum(sum, currentValue, targetValue)
    return messageTemplate(result, icon);
}
```

**Ну и на "будущее" через объект**
```js
const CURRENCY_LIST = {
    USD: { value: 90, marker: '$'},
    EUR: { value: 100, marker: '€' },
    RUB: { value: 1, marker: '₽' },
}

function isValidCurrency(currency){
    const isExists = Object.keys(CURRENCY_LIST).includes(currency);
    if(!isExists){
        console.log(`Валюта [${currency}] не поддерживается для обмена`);
    }
    return isExists;
}

function converter(value, inCurrency, outCurrency) {
    inCurrency = inCurrency.toUpperCase();
    outCurrency = outCurrency.toUpperCase();

    if (inCurrency === outCurrency) {
        return `Входящая и исходящая валюта одинаковы. Конвертация невозможна`;
    }

    // Проверяем наличие входящей валюты для обмена
    if (!isValidCurrency(inCurrency)) {
        return null;
    }
    // Проверяем наличие исходящей валюты для обмена
    if (!isValidCurrency(outCurrency)) {
        return null;
    }


    const { value: a, marker: im } = CURRENCY_LIST[inCurrency]; // im = inMarker
    const { value: b, marker: om } = CURRENCY_LIST[outCurrency]; // im = outMarker

    return `В результате обмена ${value}${im} Вы получите ${(value * a / b).toFixed(2)}${om}`
}

console.log(converter(1500, 'usd', 'usd'));
console.log(converter(1500, 'rub', 'usd'));
console.log(converter(1500, 'eur', 'usd'));
```

2024-12-25 13:24 UTC, GitEsense commented on crypto-8.js
> +console.log(check('rtyqwe', 'qwerty'));
с точки зрения работы функции `crypto` - у Вас работает корректно, однако, условие "обратимости" не выполняется, поэтому функция `check` выполняется некорректно, она берёт дешифрацию через функцию шифрования, но она не имеет обратимости, поэтому приведённое ниже условие не выполняется.

У нас будет всего две функции:
1. crypto - преобразует строку в "шифр", при повторном вызове (для шифрованной строки) - возвращает оригинальный пароль (т.е. обратимость)
2. check - получает в качестве аргументов оригинальный пароль и зашифрованный пароль, возвращает результат сравнения оригинального пароля и обратимости шифрования
Вот пример функции check:
```js
function checkPassword(encryptedPassword, originalPassword) {
    if (!encryptedPassword || !originalPassword) {
        return false;
    }
    return originalPassword === crypto(encryptedPassword);
}
```

В Вашем случае "обратимость" не выполняется, т.е. для записи вида:
```js
const p = 'password'
const e = crypto(p); // шифрованный пароль (например wosspard - зависит от вашей логики шифрования)
const d = crypto(e); // password

console.log(p,e,d, p === d); // password, wosspard, password, true
```
Результат должен быть как в указанном примере (т.е. оригинальный пароль, шифрованный, расшифрованный и сравнение оригинала и расшифрованного вернёт TRUE)


Попробуйте сделать "шифрование" более похожим на правду, перестановку символов, например у нас пароль 8 \ 10 \ 14 символов по длине, мы ищем середину и уже делим "пополам", например разворачиваем (реверс) половин, затем меняем первый и средний символ первой половины, с последним и средним символом второй половины, затем "объединяем" и возвращаем строку, для примера будет как-то так

пароль: userpassword;
длина: 12;
средний индекс: 6
первая половина: [ 'u', 's', 'e', 'r', 'p', 'a' ] - средний индекс = 3
вторая половина: [ 's', 's', 'w', 'o', 'r', 'd' ] - средний индекс = 3

меняем первый элемент (0 индекс) первого массива с четвертым (3 индекс) элементом второго массива
меняем четвертый элемент (3 индекс) первого массива с первым (0 индекс) элементом второго массива
получаем:
первая половина: [ 'o', 's', 'e', 's', 'p', 'a' ]
вторая половина: [ 'r', 's', 'w', 'u', 'r', 'd' ]

итоговая строка: osesparswurd

При выполнении:
```js
const e = crypt(password);
const d = crypt(e);
console.log(password, e ,d, password === d);
```
Получим следующий вывод 'userpassword', 'osesparswurd', 'userpassword', true

Решение такой задачки позволит "потренироваться" в перестановке элементов массива.
Поиск индексов и работа с ними, разделение массивов и сделать универсальную (обратимую) функцию

Для поиска среднего индекса подойдёт округление (Math.floor или Math.ceil) - на Ваше усмотрение
Для перестановки элементов - можете воспользоваться трюком обмена переменными
https://learn.javascript.ru/destructuring-assignment

2024-12-27 18:43 UTC, CoddeyQuinn commented on 9-sort-loops.js
> +            }
То есть это будет запись вида 
if (Massive[i] > Massive[j]) {
               [i, j] = [j, i];
     }
Правильно понимаю? Но так не получается. Либо я не в той строчке это располагаю

2024-12-27 18:45 UTC, CoddeyQuinn commented on 9-sort-loops.js
> +}
То есть все манипуляции проводить с копией? вида const clonedMassive = massive.slice();

2024-12-28 09:19 UTC, GitEsense commented on 9-sort-loops.js
> +            }
> [i, j] = [j, i];

Вы пытаетесь поменять индексы местами, а надо значения массива
```js
[arr[i], arr[j]] = [arr[j], arr[i]]
```

2024-12-28 09:21 UTC, GitEsense commented on 9-sort-loops.js
> +}
> То есть все манипуляции проводить с копией? вида const clonedMassive = massive.slice();

А можно воспользоваться и `spread` синтаксисом, но и `slice` подходит, да...
Если мы не хотим модифицировать исходный массив, тогда надо сделать копию, если же мы работаем как "оригинальный" `sort` метод - тогда мы не создаём копию

```js
const newArr = [...arr];
const newArr2 = arr.slice();
```

2025-01-06 11:58 UTC, GitEsense approved these changes
Оставил комментарии и примеры, хорошо

2025-01-06 11:58 UTC, GitEsense commented on 9-sort-loops.js
> +        for(let j = 1; j < clonedMassive.length; j++) {
из-за того, что Вы приравниваете `j = 1`, у Вас нулевой индекс всегда в пропуске, следовательно сортировка будет не полной, для сокращения кол-ва итераций лучше использовать приравнивание к `i` и чтобы не проходить сравнение "сам с собой" добавить + 1, тогда у нас будет 
`for(let j = i + 1; j < clonedMassive.length; j++)`

2025-01-06 11:58 UTC, GitEsense commented on 9-sort-loops.js
> +        for(let j = 1; j < clonedMassive.length; j++) {
Вот вариант реализации с направлением и без модификации исходного массива и с сокращением кол-ва итераций

```js
const numbers = Array.from({ length: 10 }, () => {
    const max = 100;
    const min = -100;
    const randomNumber = Math.ceil(Math.random() * (max - min)) + min;
    return randomNumber
});

function sortArray(incomingArray, desc = false) {
    const array = [...incomingArray];
    for (let i = 0; i < array.length; i++) {
        for (let j = i + 1; j < array.length; j++) {
            const isExchange = desc ? array[i] < array[j] : array[i] > array[j]
            if (isExchange) {
                [array[i], array[j]] = [array[j], array[i]];
            }
        }
    }
    return array;
}

console.log(numbers);
console.log('Отсортированный по возрастанию массив:', sortArray(numbers));
console.log('Отсортированный по убыванию массив:', sortArray(numbers, true));

2025-01-06 11:58 UTC, GitEsense commented on crypto-8.js
> +console.log(check('qwerty', crypto('qwerty')));
Всё отлично, оставлю пример реализации с генерацией пароля

```js
const CHARS = `!#$%&0123456789?@ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvw`
function crypt(password) {
    if (!password || !password.length) {
        return NaN;
    }
    const splitedArray = password.split('');
    if (splitedArray.length < 8) {
        return false;
    }

    const middleIndex = Math.floor(splitedArray.length / 2);
    const firstHalf = splitedArray.slice(0, middleIndex).reverse();
    const secondHalf = splitedArray.slice(middleIndex).reverse();
    const length = secondHalf.length;
    
    [firstHalf[1], secondHalf[length - 2]] = [secondHalf[length - 2], firstHalf[1]];
    [secondHalf[1], firstHalf[length - 2]] = [firstHalf[length - 2], secondHalf[1]];

    [firstHalf[0], secondHalf[length - 1]] = [secondHalf[length - 1], firstHalf[0]];
    [secondHalf[0], firstHalf[length - 1]] = [firstHalf[length - 1], secondHalf[0]];

    const encryptedPassword = firstHalf.concat(secondHalf);
    return encryptedPassword.join('');
}

function checkPassword(encryptedPassword, originalPassword) {
    if (!encryptedPassword || !originalPassword) {
        return false;
    }
    return originalPassword === crypt(encryptedPassword);
}

function getRandomNumber(min = 0, max = 86) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

function getRandomPassword(length = 12) {
    // const symbolArray = Array.from({ length: 87 }, (_, index) => String.fromCharCode(index + 33));
    const password = Array.from({ length }, () => CHARS[getRandomNumber(0, CHARS.length)]);
    return password.join('');
}

/*
    logging and test function with console
*/

const password = getRandomPassword();
const encrypted = crypt(password);
const decrypted = crypt(encrypted)

console.log('Пароль:', password);
console.log('Зашифрованный пароль:', encrypted);
console.log('Проверка пароля (обратимость):', decrypted === password);
console.log('Проверка пароля (check):', checkPassword(encrypted, password));
```

2025-01-12 14:42 UTC, merged